"""Drum score converter package."""

from drum_score_converter.count_in_generator import (
    COUNT_IN_BEATS,
    COUNT_IN_NOTE,
    COUNT_IN_VELOCITY,
    CountInConfig,
    CountInError,
    CountInGenerator,
)
from drum_score_converter.midi_exporter import (
    BASE_TICKS_PER_QUARTER,
    DRUM_CHANNEL,
    GM_PERCUSSION_MAPPING,
    MIDIExporter,
    MIDIExportError,
)
from drum_score_converter.musicxml_exporter import (
    INSTRUMENT_MAPPING,
    MusicXMLExporter,
    MusicXMLExportError,
    MusicXMLInstrument,
)
from drum_score_converter.openai_vision_recognizer import (
    OpenAIConfig,
    OpenAIVisionRecognizer,
)
from drum_score_converter.page_renderer import (
    DEFAULT_DPI,
    PageRenderer,
    PageRenderError,
    RenderedPage,
)
from drum_score_converter.pdf_loader import PDFDocument, PDFLoader, PDFLoadError
from drum_score_converter.recognition_model import (
    RecognitionLocation,
    RecognitionResult,
    RecognitionWarning,
    RecognitionWarningCode,
    RecognizedFraction,
    RecognizedInstrument,
    RecognizedMeasure,
    RecognizedNote,
    RecognizedPage,
    RecognizedPart,
    RecognizedRest,
    RecognizedTimeSignature,
)
from drum_score_converter.recognition_pipeline import (
    RecognitionPipeline,
    RecognitionPipelineError,
)
from drum_score_converter.score_builder import (
    InconsistentRecognitionError,
    InstrumentMappingError,
    MissingScoreDataError,
    ScoreBuilder,
    ScoreBuildError,
    ScoreConstructionError,
    UnsupportedNotationError,
)
from drum_score_converter.score_model import (
    DEFAULT_TEMPO_BPM,
    DrumInstrument,
    Measure,
    Note,
    Part,
    Rest,
    Score,
    Tempo,
    TimeSignature,
)
from drum_score_converter.vision_recognizer import (
    AuthenticationError,
    CommunicationError,
    ConfigurationError,
    InternalRecognitionError,
    ProviderResponseError,
    RecognitionConversionError,
    RecognitionError,
    VisionRecognizer,
)

__all__ = [
    "BASE_TICKS_PER_QUARTER",
    "COUNT_IN_BEATS",
    "COUNT_IN_NOTE",
    "COUNT_IN_VELOCITY",
    "DEFAULT_DPI",
    "DEFAULT_TEMPO_BPM",
    "DRUM_CHANNEL",
    "DrumInstrument",
    "CountInConfig",
    "CountInError",
    "CountInGenerator",
    "GM_PERCUSSION_MAPPING",
    "INSTRUMENT_MAPPING",
    "Measure",
    "MIDIExporter",
    "MIDIExportError",
    "MusicXMLExporter",
    "MusicXMLExportError",
    "MusicXMLInstrument",
    "Note",
    "OpenAIConfig",
    "OpenAIVisionRecognizer",
    "Part",
    "PDFDocument",
    "PDFLoader",
    "PDFLoadError",
    "PageRenderer",
    "PageRenderError",
    "Rest",
    "RecognitionLocation",
    "RecognitionPipeline",
    "RecognitionPipelineError",
    "RecognitionConversionError",
    "RecognitionError",
    "RecognitionResult",
    "RecognitionWarning",
    "RecognitionWarningCode",
    "RecognizedFraction",
    "RecognizedInstrument",
    "RecognizedMeasure",
    "RecognizedNote",
    "RecognizedPage",
    "RecognizedPart",
    "RecognizedRest",
    "RecognizedTimeSignature",
    "RenderedPage",
    "Score",
    "ScoreBuildError",
    "ScoreBuilder",
    "ScoreConstructionError",
    "Tempo",
    "TimeSignature",
    "UnsupportedNotationError",
    "VisionRecognizer",
    "AuthenticationError",
    "CommunicationError",
    "ConfigurationError",
    "InternalRecognitionError",
    "ProviderResponseError",
    "InconsistentRecognitionError",
    "InstrumentMappingError",
    "MissingScoreDataError",
]

